FilmsCatalog/Controllers/FilmsController.cs
using FilmsCatalog.Data.Interface;
using FilmsCatalog.Filters;
using FilmsCatalog.Models;
using FilmsCatalog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Controllers
{
    public class FilmsController : Controller
    {
        /// <summary>
        /// Фильмы
        /// </summary>
        private readonly IFilm films;

        /// <summary>
        /// Режиссёры
        /// </summary>
        private readonly IProducer producers;

        /// <summary>
        /// Постеры фильмов
        /// </summary>
        private readonly IPoster posters;

        private readonly SignInManager<User> _signInManager;

        public FilmsController(IFilm films, IProducer producers, IPoster posters, SignInManager<User> signInManager)
        {
            this.films = films;
            this.producers = producers;
            this.posters = posters;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index(int page = 1, int count = 12)
        {
            int countRecord = await films.GetCount();

            FilmsIndexViewModel model = new()
            {
                Page = new(countRecord, page, count)
            };

            var items = await films.GetFilmsAsync(page, count);
            if (items.Count > 0)
            {
                model.Films = items
                    .Select(c => new FilmViewModel
                    {
                        Id = c.Id,
                        Name = c.Name,
                        Description = c.Description,
                        PosterId = c.PosterId,
                        Producer = c.Producer != null ? c.Producer.Name : "",
                        Year = c.Year
                    })
                    .ToList();
            }

            return PartialView(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Film film = await films.GetAsync((int)id);
            if (film == null)
            {
                return NotFound();
            }

            FilmDetailsViewModel model = new()
            {
                Id = film.Id,
                UserId = film.UserId,
                Name = film.Name,
                Description = film.Description,
                Year = film.Year,
                Producer = film.Producer?.Name,
                PosterId = film.Poster?.Id
            };

            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(FilmCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Create));
            }
            int? producerId = null;
            if (!string.IsNullOrEmpty(model.Producer))
            {
                producerId = producers.LoadOrCreate(model.Producer);
            }
            int? posterId = null;
            if (model.Poster != null)
            {
                posterId = await posters.AddAsync(model.Poster);
            }

            Film film = new()
            {
                Year = model.Year,
                Name = model.Name,
                Description = model.Description,
                PosterId = posterId,
                ProducerId = producerId,
                UserId = _signInManager.UserManager.GetUserId(User)
            };

            if (await films.AddAsync(film))
            {
                return RedirectToAction(nameof(Edit), new { id = film.Id });
            }
            ModelState.AddModelError(string.Empty, "Ошибка при сохранении");
            return RedirectToAction(nameof(Create));
        }

        [ServiceFilter(typeof(AuthorFilter))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await films.GetAsync((int)id);
            if (film == null)
            {
                return NotFound();
            }
            FilmEditViewModel model = new()
            {
                Id = film.Id,
                Name = film.Name,
                Description = film.Description,
                PosterId = film.PosterId,
                Producer = film.Producer?.Name,
                Year = film.Year
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(AuthorFilter))]
        public async Task<IActionResult> Edit(FilmEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Edit), new { id = model.Id });
            }
            var item = await films.GetAsync(model.Id);
            if (item == null)
            {
                return NotFound();
            }

            if (model.Producer != item.Producer?.Name)
            {
                item.ProducerId = producers.LoadOrCreate(model.Producer);
            }

            if (model.Poster != null)
            {
                int newPosterId = await posters.AddAsync(model.Poster);
                if (newPosterId > 0 && item.PosterId != null)
                {
                    await posters.DeleteAsync((int)item.PosterId);
                }
                item.PosterId = newPosterId;
            }

            item.Name = model.Name;
            item.Description = model.Description;
            item.Producer = null;
            item.Year = model.Year;
            await films.SaveAsync(item);

            return RedirectToAction(nameof(Edit), new { id = item.Id });
        }

        [ServiceFilter(typeof(AuthorFilter))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await films.GetAsync((int)id);
            if (film == null)
            {
                return NotFound();
            }

            FilmDetailsViewModel model = new()
            {
                Id = film.Id,
                UserId = film.UserId,
                Name = film.Name,
                Description = film.Description,
                Year = film.Year,
                Producer = film.Producer.Name,
                PosterId = film.Poster?.Id
            };

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(AuthorFilter))]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await films.GetAsync(id);

            if (item == null)
            {
                return NotFound();
            }

            if (item.PosterId != null)
            {
                await posters.DeleteAsync((int)item.PosterId);
            }
            await films.DeleteAsync(item.Id);

            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

FilmsCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Каталог фильмов</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="~/css/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Каталог фильмов</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Films" asp-action="Create">Добавить фильм</a>
                            </li>
                        }
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Каталог фильмов
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>